# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93266f0a6ea00f81def82e6ea7cfe6ed4dfd53c4d3d5dce669fa667d5288f98cef8e00776fc257fe584a21ec7af6e094064057083ad693292e8cc0026f5d0604

test:
  secret_key_base: cf59684290c952a0929c41ec42128981bcbec78ad7232f728d4e9eb8afdbfd7ab63fb969d999355a8b9f8574cf14c38d6ab0a1692923b19faad6fbd3f632fa8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
